assume -name {i_BLT_0} {i0[14:12] == 3'b100}
assume -name {i_BLT_1} {i0[6:0] == 7'b1100011}
cover -name cvr_div_s1 {(@(posedge clk_i) div_s1)}
cover -name cvr_div_s2 {(@(posedge clk_i) div_s2)}
cover -name cvr_decode_s1 {(@(posedge clk_i) decode_s1)}
cover -name cvr_issue_s1 {(@(posedge clk_i) issue_s1)}
cover -name cvr_issue_s2 {(@(posedge clk_i) issue_s2)}
cover -name cvr_issue_s8 {(@(posedge clk_i) issue_s8)}
cover -name cvr_issue_s16 {(@(posedge clk_i) issue_s16)}
cover -name cvr_issue_s32 {(@(posedge clk_i) issue_s32)}
cover -name cvr_lsq_enq_0_s1 {(@(posedge clk_i) lsq_enq_0_s1)}
cover -name cvr_lsq_enq_1_s1 {(@(posedge clk_i) lsq_enq_1_s1)}
cover -name cvr_scb_0_s8 {(@(posedge clk_i) scb_0_s8)}
cover -name cvr_scb_0_s12 {(@(posedge clk_i) scb_0_s12)}
cover -name cvr_scb_0_s13 {(@(posedge clk_i) scb_0_s13)}
cover -name cvr_scb_0_s14 {(@(posedge clk_i) scb_0_s14)}
cover -name cvr_scb_1_s8 {(@(posedge clk_i) scb_1_s8)}
cover -name cvr_scb_1_s12 {(@(posedge clk_i) scb_1_s12)}
cover -name cvr_scb_1_s13 {(@(posedge clk_i) scb_1_s13)}
cover -name cvr_scb_1_s14 {(@(posedge clk_i) scb_1_s14)}
cover -name cvr_scb_2_s8 {(@(posedge clk_i) scb_2_s8)}
cover -name cvr_scb_2_s12 {(@(posedge clk_i) scb_2_s12)}
cover -name cvr_scb_2_s13 {(@(posedge clk_i) scb_2_s13)}
cover -name cvr_scb_2_s14 {(@(posedge clk_i) scb_2_s14)}
cover -name cvr_scb_3_s8 {(@(posedge clk_i) scb_3_s8)}
cover -name cvr_scb_3_s12 {(@(posedge clk_i) scb_3_s12)}
cover -name cvr_scb_3_s13 {(@(posedge clk_i) scb_3_s13)}
cover -name cvr_scb_3_s14 {(@(posedge clk_i) scb_3_s14)}
cover -name cvr_stb_com_0_s1 {(@(posedge clk_i) stb_com_0_s1)}
cover -name cvr_stb_com_1_s1 {(@(posedge clk_i) stb_com_1_s1)}
cover -name cvr_stb_spec_0_s1 {(@(posedge clk_i) stb_spec_0_s1)}
cover -name cvr_stb_spec_1_s1 {(@(posedge clk_i) stb_spec_1_s1)}
cover -name cvr_load_unit_s1 {(@(posedge clk_i) load_unit_s1)}
cover -name cvr_store_unit_s1 {(@(posedge clk_i) store_unit_s1)}
cover -name cvr_store_unit_s3 {(@(posedge clk_i) store_unit_s3)}
cover -name cvr_load_unit_buff_s1 {(@(posedge clk_i) load_unit_buff_s1)}
cover -name cvr_csr_buffer_s1 {(@(posedge clk_i) csr_buffer_s1)}
cover -name cvr_mult_s1 {(@(posedge clk_i) mult_s1)}
cover -name cvr_load_unit_op_s1 {(@(posedge clk_i) load_unit_op_s1)}
cover -name cvr_load_unit_op_s2 {(@(posedge clk_i) load_unit_op_s2)}
cover -name cvr_load_unit_op_s3 {(@(posedge clk_i) load_unit_op_s3)}
cover -name cvr_mem_req_s1 {(@(posedge clk_i) mem_req_s1)}
